### ISSUE TITLE
Dependencies Resolution

### ISSUE THREAD

**Issue by naveeng2402** [lautr/initium-nuxt#387]
Hi @lautr really interested by your work and excited, but I'm having several doubts on how the dependencies are managed between the vue app and nuxt app,

You've using tailwind in both of them but in nuxt we have tailwindcss module is it possible to use that and how can we synchronise the tailwindconfig.

Can you shed some light on how dependencies between these projects are integrated.

**Comment by lautr** [comment]
Hi @naveeng2402,

Thank you for expressing interest in my project. I originally chose to use Tailwind directly, rather than utilizing a module, in order to simplify the process of ensuring that both the design system and applications utilize the same Tailwind version.

However, I am currently working on adding Nuxt Layer support to facilitate the integration of multiple Nuxt applications. In doing so, I plan to transition to Nuxt Tailwind, as it streamlines various tasks, and i will also centralize the Tailwind configuration. Although this enhancement is still a work in progress, you can take a look: https://github.com/lautr/initium-nuxt/pull/349.

Regarding dependencies, I designed the approach so that both the applications and the design system can function independently, without any indirect or hidden dependencies. The sole exception is the inclusion of ESLint and TypeScript, which are defined at the monorepo level. I made this decision as a compromise in order to improve the overall developer experience.

If you have any additional questions or suggestions for enhancing the starter kit, please don't hesitate.

**Comment by naveeng2402** [comment]
Hi @lautr, exploring on the setup and tried a similar approach on an actual product and now I'm here with some suggestions

- Get a way to integrate iconify for nuxt we have `Nuxt Icon` and for vue, we have `iconify/vue` but also found that iconify also has a web component. I'm not too familiar with them so I'm unable to make the intelliscense work.
- We may need to figure out how to add `nuxt-image` support which not only has amazing optimisation features but also integrates seamlessly with cloud images from various sources such as cloudinary
- Additonally we can also add a composables directory to the vue app, so that we can able to create renderless components and have a robust design system
